PREFIX schema: <http://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT 
  ?eventType
  (COALESCE(?prefLabel, "No Artsdata Event Type"@en) AS ?prefLabelOrDefault)
  ?deprecated
  (COUNT(DISTINCT ?event) AS ?count)
WHERE {
  ?event a schema:Event .
  OPTIONAL {
    ?event schema:additionalType ?eventType .
    ?eventType skos:inScheme <http://kg.artsdata.ca/resource/ArtsdataEventTypes> .
    ?eventType skos:prefLabel ?prefLabel .
    FILTER(lang(?prefLabel) = "en")
    OPTIONAL { ?eventType owl:deprecated ?deprecated }
  }
}
GROUP BY ?eventType ?prefLabel ?deprecated
ORDER BY DESC(?count)
