PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select 
?eventType 
?prefLabel 
?deprecated 
?parent 
?definition
?version3
?version4 
?changeNote 
?replacedBy 
?editorialNote
where {
    ?eventType skos:inScheme <http://kg.artsdata.ca/resource/ArtsdataEventTypes> .
    ?eventType skos:prefLabel ?prefLabel .
    OPTIONAL {
        ?eventType owl:deprecated ?deprecated
    }
    OPTIONAL {
        ?eventType skos:broader ?parent .
    }
    filter(lang(?prefLabel) = "en")
    OPTIONAL {
        ?eventType skos:definition ?definition .
        filter(lang(?definition) = "en")
    }
    OPTIONAL {
        <http://kg.artsdata.ca/resource/ArtsdataEventTypes-Collection-3.4>  skos:member   ?eventType  ;
        bind(true as ?version3)
    }
    OPTIONAL {
        <http://kg.artsdata.ca/resource/ArtsdataEventTypes-Collection-4.0>  skos:member   ?eventType  ;
        bind(true as ?version4)
    }
    OPTIONAL {
        ?eventType skos:changeNote ?changeNote .
    }
    OPTIONAL {
        ?eventType <http://purl.org/dc/terms/isReplacedBy>   ?replacedBy
    }
    OPTIONAL {
        ?eventType skos:editorialNote ?editorialNote .
        filter(lang(?editorialNote) = "en")
    }
}
