PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select 
?eventType 
?prefLabel 
?deprecated 
?parent 
?definition
?version3
?version4 
?v4changeNote 
?replacedBy 
?editorialNote
where {
    ?eventType skos:inScheme <http://kg.artsdata.ca/resource/ArtsdataEventTypes> .
    ?eventType skos:prefLabel ?prefLabel .
    OPTIONAL {
        ?eventType owl:deprecated ?deprecated
    }
    OPTIONAL {
        ?eventType skos:broader ?parent .
    }
    filter(lang(?prefLabel) = "en")
    OPTIONAL {
        ?eventType skos:definition ?definition .
        filter(lang(?definition) = "en")
    }
    OPTIONAL {
        ?v3  skos:member   ?eventType  ;
        schema:version "3.4.5".
        bind(!BOUND(?v3) as ?version3)
    }
    OPTIONAL {
        ?v4  skos:member   ?eventType  ;
        schema:version "4.0".
         bind(!BOUND(?v4) as ?version4)
    }
    OPTIONAL {
        ?eventType skos:changeNote/rdf:value ?v4changeNote .
    }
    OPTIONAL {
        ?eventType <http://purl.org/dc/terms/isReplacedBy>   ?replacedBy
    }
    OPTIONAL {
        ?eventType skos:editorialNote ?editorialNote .
        filter(lang(?editorialNote) = "en")
    }
}
