PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
select * where {
    ?s skos:prefLabel ?prefLabel .
    OPTIONAL {
        ?s owl:deprecated ?deprecated
    }
    ?s skos:inScheme <http://kg.artsdata.ca/resource/ArtsdataEventTypes> .
    OPTIONAL {
        ?s skos:broader ?parent .
    }
    filter(lang(?prefLabel) = "en")
    OPTIONAL {
        ?s skos:definition ?definition .
        filter(lang(?definition) = "en")
    }
    OPTIONAL {
        ?collection3  skos:member   ?s  ;
        schema:version "3.4.5".
    }
    OPTIONAL {
        ?collection4  skos:member   ?s  ;
        schema:version "4.0".
    }
    OPTIONAL {
        ?s skos:changeNote/rdf:value ?collection4changeNote .
    }
    OPTIONAL {
        ?s <http://purl.org/dc/terms/isReplacedBy>   ?replacedBy
    }
    OPTIONAL {
        ?s skos:editorialNote ?editorialNote .
        filter(lang(?editorialNote) = "en")
    }
} limit 100
