PREFIX schema: <http://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
select * where {
    ?ad_event schema:sameAs ?event ;
              a schema:Event ;
              schema:startDate ?startDate .
    optional {
        ?ad_event schema:eventStatus ?eventStatus .
    }
    filter(isURI(?event))
    filter(contains(str(?ad_event),"kg.artsdata.ca"))
    filter(not exists {
            ?event schema:name ?name 
        })
    filter(not exists {
            ?ad_event schema:eventStatus schema:EventCancelled 
        })
    filter(?startDate > now())
    #  << ?ad_event schema:sameAs ?event >> prov:wasDerivedFrom/foaf:primaryTopic/<http://dataid.dbpedia.org/ns/core#artifact> ?artifact .
    #  values ?artifact {<http://kg.artsdata.ca/databus/culture-creates/footlight/co-motion-ca>}
}
