PREFIX schema: <http://schema.org/>

# Diagnose mint collisions by looking for minted entities with 2 mint generatedAtTime dates
select ?event 
(SAMPLE(?names) as ?name)
(SAMPLE(?location_names) as ?location_name)
?mint_date
where {
    {
        select   ?event (SAMPLE(?generatedAt) as ?mint_date) where {
            graph <http://kg.artsdata.ca/core> {
                ?event a schema:Event ;
                <http://www.w3.org/ns/prov#generatedAtTime> ?generatedAt .
            } 
        } group by ?event HAVING (COUNT(?generatedAt) > 1)
    }
    graph <http://kg.artsdata.ca/core> {
        ?event   schema:name ?names ;
        schema:location/schema:name ?location_names .
    }
}  group by ?event ?mint_date
