PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX luc: <http://www.ontotext.com/connectors/lucene#>
PREFIX luc-index: <http://www.ontotext.com/connectors/lucene/instance#>
PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX adr: <http://kg.artsdata.ca/resource/>
select distinct ?event ?event_name  ?startDate ?linked_performer_name ?score ?agent_name ?artsdataid_uri ?type_sample   
where {
    {
        select   (sample(?name) as ?agent_name)  ?artsdataid_uri  (sample(?type) as ?type_sample)  ?wdid_uri where {
            {
                select distinct ?artsdataid_uri where {
                    VALUES ?artsdataid_uri {
                        adr:K2-5073
                        adr:K2-5016
                        adr:K2-139
                        adr:K2-108
                        adr:K2-5765
                        adr:K2-5018
                        adr:K2-89
                        adr:K2-5769
                        adr:K2-5034
                        adr:K2-5759
                        adr:K2-178
                        adr:K2-6447
                        adr:K2-5734
                        adr:K2-6332
                        adr:K2-6316
                        adr:K3-39
                        adr:K2-5037
                        adr:K2-6116
                        adr:K2-6152
                        adr:K2-6239
                        adr:K2-6308
                        adr:K2-6314
                        adr:K2-6789
                        adr:K2-98
                        adr:K12-6
                        adr:K2-48
                        adr:K2-4887
                        adr:K2-5734
                        adr:K2-5007
                        adr:K3-137
                        adr:K3-210
                        adr:K2-5077
                        adr:K2-5866
                        adr:K2-6137
                        adr:K2-6307
                        adr:K2-6311
                        adr:K2-6317
                        adr:K2-5004
                        adr:K2-6290
                        adr:K3-62
                        adr:K3-15
                        adr:K10-9
                        adr:K2-5049
                        adr:K3-11
                        adr:K3-20
                        adr:K3-22
                        adr:K3-25
                        adr:K3-31
                        adr:K3-45
                        adr:K3-46
                        adr:K3-51
                        adr:K3-56
                        adr:K3-61
                        adr:K3-63
                        adr:K3-71
                        adr:K3-78
                        adr:K3-80
                        adr:K3-86
                        adr:K3-99
                        adr:K3-100
                        adr:K3-102
                        adr:K3-104
                        adr:K3-106
                        adr:K3-130
                        adr:K3-147
                        adr:K3-167
                        adr:K3-169
                        adr:K2-5009
                        adr:K2-5033
                        adr:K2-5015
                        adr:K2-5022
                        adr:K3-198
                        adr:K3-212
                        adr:K2-5082
                        adr:K2-5097
                        adr:K2-6422
                        adr:K2-5376
                        adr:K2-5184
                        adr:K2-5189
                        adr:K2-5540
                        adr:K2-6138
                        adr:K2-6218
                        adr:K2-6243
                        adr:K2-6373
                        adr:K2-6791
                        adr:K2-86
                        adr:K2-5732
                        adr:K2-69
                        adr:K2-125
                        adr:K2-41
                        adr:K3-199
                        adr:K2-5306
                        adr:K2-5052
                        adr:K12-447
                        adr:K2-5553
                        adr:K2-5083
                        adr:K3-33
                        adr:K2-5531
                        adr:K2-5736
                        adr:K2-5081
                        adr:K2-177
                        adr:K2-176
                        adr:K3-70
                        adr:K2-5025
                        adr:K3-141
                        adr:K3-35
                        adr:K3-83
                        adr:K3-119
                        adr:K3-143
                        adr:K2-5001
                        adr:K2-5549
                        adr:K2-5552
                        adr:K2-5606
                        adr:K2-5770
                        adr:K2-6238
                        adr:K2-6238
                        adr:K2-6244
                        adr:K2-6377
                        adr:K2-6421
                        adr:K2-6778
                        adr:K2-6782
                        adr:K3-53
                        adr:K3-59
                        adr:K3-149
                        adr:K3-156
                        adr:K3-174
                        adr:K3-1
                        adr:K3-2
                        adr:K17-24
                        adr:K3-8
                        adr:K3-9
                        adr:K3-10
                        adr:K3-12
                        adr:K3-13
                        adr:K3-16
                        adr:K3-17
                        adr:K3-19
                        adr:K3-21
                        adr:K3-23
                        adr:K3-24
                        adr:K3-27
                        adr:K3-28
                        adr:K3-29
                        adr:K3-30
                        adr:K3-32
                        adr:K3-34
                        adr:K3-35
                        adr:K3-36
                        adr:K3-37
                        adr:K3-38
                        adr:K3-39
                        adr:K3-40
                        adr:K3-42
                        adr:K3-43
                        adr:K3-44
                        adr:K3-47
                        adr:K3-48
                        adr:K3-50
                        adr:K3-52
                        adr:K3-54
                        adr:K3-57
                        adr:K3-60
                        adr:K3-64
                        adr:K3-65
                        adr:K3-66
                        adr:K3-67
                        adr:K3-68
                        adr:K3-69
                        adr:K3-72
                        adr:K3-73
                        adr:K3-74
                        adr:K3-75
                        adr:K3-79
                        adr:K3-82
                        adr:K3-84
                        adr:K3-89
                        adr:K3-92
                        adr:K3-94
                        adr:K3-95
                        adr:K3-96
                        adr:K3-98
                        adr:K3-101
                        adr:K3-105
                        adr:K3-108
                        adr:K3-109
                        adr:K3-110
                        adr:K3-113
                        adr:K3-114
                        adr:K3-115
                        adr:K3-117
                        adr:K3-118
                        adr:K3-119
                        adr:K3-121
                        adr:K3-123
                        adr:K3-124
                        adr:K3-125
                        adr:K3-126
                        adr:K3-127
                        adr:K3-128
                        adr:K3-129
                        adr:K3-131
                        adr:K3-133
                        adr:K3-134
                        adr:K3-135
                        adr:K3-136
                        adr:K3-138
                        adr:K3-139
                        adr:K3-140
                        adr:K3-142
                        adr:K3-143
                        adr:K3-144
                        adr:K3-145
                        adr:K3-146
                        adr:K3-148
                        adr:K3-150
                        adr:K3-152
                        adr:K3-153
                        adr:K3-154
                        adr:K3-155
                        adr:K3-157
                        adr:K3-158
                        adr:K3-122
                        adr:K2-5016
                        adr:K3-26
                        adr:K3-90
                        adr:K3-160
                        adr:K12-446
                        adr:K3-116
                        adr:K3-58
                        adr:K3-111
                        adr:K3-41
                        adr:K3-91
                        adr:K3-93
                        adr:K3-70
                        adr:K3-6
                        adr:K3-97
                        adr:K3-141
                        adr:K3-132
                        adr:K3-3
                        adr:K3-14
                        adr:K3-105
                        adr:K3-112
                        adr:K3-120
                        adr:K3-127
                        adr:K2-5050
                        adr:K2-5039
                        adr:K2-5056
                        adr:K2-5786
                        adr:K2-6240
                        adr:K2-6311
                        adr:K2-6320
                        adr:K2-5020
                        adr:K2-147
                        adr:K2-5737
                        adr:K2-5568
                        adr:K2-6191
                        adr:K2-5213
                        adr:K2-5036
                        adr:K2-3346
                        adr:K3-159
                        adr:K3-161
                        adr:K3-163
                        adr:K3-165
                        adr:K3-168
                        adr:K3-170
                        adr:K3-172
                        adr:K3-173
                        adr:K3-55
                        adr:K2-6241
                        adr:K2-6787
                        adr:K2-5079
                        adr:K2-5017
                        adr:K2-5177
                        adr:K2-51
                        adr:K2-6192
                        adr:K2-48
                        adr:K2-104
                        adr:K2-5019
                        adr:K2-5038
                        adr:K2-5024
                        adr:K2-5065
                        adr:K2-5185
                        adr:K2-5551
                        adr:K2-5566
                        adr:K2-5786
                        adr:K2-6238
                        adr:K2-6377
                        adr:K2-5996
                        adr:K2-62
                        adr:K2-5718
                        adr:K2-5532
                        adr:K3-97
                        adr:K2-5046
                        adr:K2-54
                        adr:K2-68
                        adr:K2-86
                        adr:K2-5003
                        adr:K2-58
                        adr:K2-81
                        adr:K12-465
                        adr:K2-5030
                        adr:K2-136
                        adr:K3-58
                        adr:K2-5071
                        adr:K2-5533
                        adr:K3-6
                        adr:K2-5002
                        adr:K3-2
                        adr:K3-57
                        adr:K3-140
                        adr:K3-210
                        adr:K2-5080
                        adr:K2-5612
                        adr:K2-6378
                        adr:K2-6427
                        adr:K2-6785
                        adr:K2-5052
                        adr:K2-5534
                        adr:K2-76
                        adr:K2-75
                        adr:K2-144
                        adr:K2-143
                        adr:K2-5151
                        adr:K2-5042
                        adr:K2-148
                        adr:K2-5536
                        adr:K2-90
                        adr:K2-98
                        adr:K2-29
                        adr:K2-140
                        adr:K2-5023
                        adr:K2-119
                        adr:K2-117
                        adr:K2-113
                        adr:K2-105
                        adr:K2-5602
                        adr:K2-104
                        adr:K2-106
                        adr:K3-41
                        adr:K2-109
                        adr:K3-93
                        adr:K2-5025
                        adr:K2-5019
                        adr:K2-5049
                        adr:K3-1
                        adr:K17-24
                        adr:K3-150
                        adr:K3-152
                        adr:K2-5006
                        adr:K2-5013
                        adr:K3-220
                        adr:K3-212
                        adr:K3-206
                        adr:K2-5040
                        adr:K2-5084
                        adr:K2-5085
                        adr:K2-5062
                        adr:K2-5343
                        adr:K2-5611
                        adr:K2-5730
                        adr:K2-5765
                        adr:K2-5866
                        adr:K2-6151
                        adr:K2-6306
                        adr:K2-26
                        adr:K2-25
                        adr:K2-83
                        adr:K2-95
                        adr:K2-87
                        adr:K12-438
                        adr:K12-182
                        adr:K2-50
                        adr:K12-296
                        adr:K2-67
                        adr:K2-72
                        adr:K2-73
                        adr:K2-146
                        adr:K2-85
                        adr:K2-44
                        adr:K2-9
                        adr:K2-28
                        adr:K2-49
                        adr:K2-80
                        adr:K2-163
                        adr:K2-79
                        adr:K2-78
                        adr:K2-71
                        adr:K2-134
                        adr:K2-96
                        adr:K2-1
                        adr:K2-30
                        adr:K2-6
                        adr:K2-77
                        adr:K2-148
                        adr:K2-149
                        adr:K2-5026
                        adr:K2-132
                        adr:K2-29
                        adr:K2-140
                        adr:K2-5023
                        adr:K2-119
                        adr:K3-151
                        adr:K3-33
                        adr:K2-5012
                        adr:K2-135
                        adr:K2-120
                        adr:K2-4
                        adr:K2-114
                        adr:K2-10
                        adr:K2-11
                        adr:K2-124
                        adr:K2-18
                        adr:K2-22
                        adr:K2-23
                        adr:K2-13
                        adr:K2-111
                        adr:K2-115
                        adr:K2-15
                        adr:K2-12
                        adr:K2-116
                        adr:K2-112
                        adr:K2-118
                        adr:K2-17
                        adr:K2-14
                        adr:K2-24
                        adr:K2-122
                        adr:K2-19
                        adr:K2-121
                        adr:K2-5045
                        adr:K2-34
                        adr:K2-128
                        adr:K2-38
                        adr:K2-129
                        adr:K2-40
                        adr:K2-131
                        adr:K2-35
                        adr:K2-42
                        adr:K2-127
                        adr:K2-126
                        adr:K2-37
                        adr:K2-130
                        adr:K2-45
                        adr:K2-36
                        adr:K2-166
                        adr:K2-160
                        adr:K2-154
                        adr:K2-170
                        adr:K2-172
                        adr:K2-47
                        adr:K2-43
                        adr:K2-165
                        adr:K2-164
                        adr:K2-152
                        adr:K2-169
                        adr:K2-167
                        adr:K2-153
                        adr:K2-161
                        adr:K2-157
                        adr:K2-46
                        adr:K2-60
                        adr:K2-158
                        adr:K2-159
                        adr:K2-56
                        adr:K2-156
                        adr:K2-162
                        adr:K2-155
                        adr:K2-61
                        adr:K2-151
                        adr:K2-171
                        adr:K2-174
                        adr:K2-173
                        adr:K2-103
                        adr:K2-101
                        adr:K2-102
                        adr:K2-107
                        adr:K2-5008
                        adr:K3-76
                        adr:K3-215
                        adr:K3-4
                        adr:K3-7
                        adr:K3-49
                        adr:K3-162
                        adr:K2-5046
                        adr:K2-5055
                        adr:K12-475
                        adr:K2-1295
                        adr:K2-5044
                        adr:K3-209
                        adr:K3-221
                        adr:K2-5048
                        adr:K2-5011
                        adr:K2-5021
                        adr:K2-6140
                        adr:K2-6184
                        adr:K2-6427
                        adr:K2-6779
                        adr:K2-5052
                        adr:K2-53
                        adr:K3-107
                        adr:K2-145
                        adr:K2-6136
                        adr:K2-5732
                        adr:K2-27
                        adr:K2-64
                        adr:K2-5091
                        adr:K4-147
                        adr:K2-5740
                        adr:K2-5103
                        adr:K2-5106
                        adr:K2-5112
                        adr:K2-5088
                        adr:K2-5095
                        adr:K2-5896
                        adr:K2-5092
                        adr:K2-280
                        adr:K10-179
                        adr:K3-181
                        adr:K2-5099
                        adr:K2-5110
                        adr:K2-5093
                        adr:K2-5102
                        adr:K2-5100
                        adr:K10-511
                        adr:K2-5107
                        adr:K2-5098
                        adr:K2-5111
                        adr:K2-5105
                        adr:K2-5872
                        adr:K2-5897
                        adr:K10-206
                        adr:K2-5090
                        adr:K2-288
                        adr:K2-289
                        adr:K14-165
                        adr:K2-6316
                        adr:K14-81
                        adr:K14-89
                        adr:K2-5101
                        adr:K2-282
                        adr:K2-291
                        adr:K2-276
                        adr:K2-286
                        adr:K2-283
                        adr:K2-277
                        adr:K2-278
                        adr:K2-287
                        adr:K2-5094
                        adr:K2-5089
                        adr:K2-5104
                        adr:K3-190
                        adr:K2-5108
                        adr:K2-5109
                        adr:K14-132
                        adr:K2-5411
                        adr:K2-5301
                        adr:K2-5303
                        adr:K2-5347
                        adr:K5-968
                        adr:K2-5535
                        adr:K2-5537
                        adr:K3-205
                        adr:K2-5763
                        adr:K2-5881
                        adr:K2-5908
                        adr:K2-5898
                        adr:K2-5907
                        adr:K2-5937
                        adr:K2-6107
                        adr:K2-6130
                        adr:K2-6132
                        adr:K2-6139
                        adr:K2-6153
                        adr:K2-6154
                        adr:K2-6187
                        adr:K2-6225
                    }
                }
            }
            graph ?g {
                ?artsdataid_uri a ?type ;
                schema:name ?name .
            }
        } group by ?artsdataid_uri  ?wdid_uri 
    }
    bind(replace(str(?agent_name),"\"|/"," ")  as ?str)
    ?search a luc-index:event-index ;
    luc:query ?str;
    luc:entities ?event .
    graph ?g {
        ?event schema:startDate ?startDate .
    }
    ?event luc:score ?score ;
    rdfs:label ?event_name .
    optional {
        ?event schema:performer/schema:name ?linked_performer_optional_name 
    }
    bind(coalesce(?linked_performer_optional_name,"") as ?linked_performer_name)
    filter(?startDate > now())
    filter(?score > 5.0)
    filter(str(?linked_performer_name) != str(?agent_name) )
    filter(?g != <http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/indigenous-performances>)
} order by DESC(?score)
