PREFIX schema: <http://schema.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

select ?type ?label (count(?s) as ?count) where { 
	?s a schema:Event ; a ?type .
    optional {?type rdfs:label ?label }
    
} group by ?type ?label order by DESC(?label)
