# List of graphs with their ranking
PREFIX schema: <http://schema.org/>
PREFIX shacl: <http://www.w3.org/ns/shacl#>
PREFIX prov: <http://www.w3.org/ns/prov#>

select * 
where {
  ?graph a schema:DataFeed ; 
           schema:maintainer ?maintainer ; 
           schema:contentRating/schema:ratingValue ?ratingValue ;
           schema:contentRating/schema:ratingValue ?ratingExplanation ;
          prov:generatedAtTime ?generatedAtTime .
  }
