# List of graphs with their ranking
PREFIX schema: <http://schema.org/>
PREFIX shacl: <http://www.w3.org/ns/shacl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
select * 
where {
    ?graph a schema:Dataset ;
           schema:name ?name .
    OPTIONAL {
       ?graph prov:generatedAtTime ?generatedAtTime .
    }
    OPTIONAL {
        ?graph  schema:maintainer ?maintainer .
    }
    OPTIONAL {
        ?graph schema:contentRating/schema:ratingValue ?ratingValue .
    }
    OPTIONAL {
        ?graph  schema:contentRating/schema:ratingExplanation ?ratingExplanation .
    }
} order by DESC(?ratingValue)
