PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ado: <http://kg.artsdata.ca/ontology/>
PREFIX adp: <http://kg.artsdata.ca/plugin#>
PREFIX schema: <http://schema.org/>
SELECT  ?entity_uri ?entity_name (MAX(?type) AS ?entity_type) where {
    GRAPH <http://kg.artsdata.ca/core> {
        {
            {
                ?entity_uri a schema:Person  .
            } MINUS {
                ?entity_uri a ado:Person .
            }
        }
        UNION
        {
            {
                ?entity_uri a schema:Place  .
            } MINUS {
                ?entity_uri a ado:Place .
            }
        }
        UNION
        {
            {
                ?entity_uri a schema:Organization  .
            } MINUS {
                ?entity_uri a ado:Organization .
            }
        }
        UNION
        {
            {
                ?entity_uri a schema:Event  .
            } MINUS {
                ?entity_uri a ado:Event .
            }
        }
        FILTER(!isBLANK(?entity_uri))
        BIND(adp:prefLangLiteral(?entity_uri, schema:name, "en fr") AS ?entity_name)
        ?entity_uri a ?type.
    }
} GROUP BY ?entity_uri ?entity_name
ORDER BY ?entity_uri ?type ?entity_name
