PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>


select  ?event (sample(?historyNote) as ?historyNote)  (sample(?type) as ?type)  (count(?p) as ?prop_count)
where {
    ?event a schema:Event .
    graph <http://kg.artsdata.ca/core> {
        ?event a ?type ; 
        skos:historyNote ?historyNote ; 
        ?p ?o .
        OPTIONAL {
            ?event schema:name ?name .
        }
    }
    filter(!bound(?name))

}  group by ?event  
