PREFIX schema: <http://schema.org/>
SELECT  
?artsdata  
?nom 
?contained_in  
?wikidata  
(sample(?streetAddresses) as ?streetAddress) 
(sample(?localities) as ?locality) 
(sample(?regions) as ?region) 
(sample(?postalCodes) as ?postalCode)
(sample(?countries) as ?country)
where {
    ?artsdata a schema:Place .
    OPTIONAL {
        ?artsdata schema:containedInPlace ?contained_in .
        filter(contains(str(?contained_in),"http://kg.artsdata.ca/resource/K"))
    }
    OPTIONAL {
        ?artsdata schema:name ?name_fr .
        filter(lang(?name_fr) = "fr")
    }
    OPTIONAL {
        ?artsdata schema:name ?name_en .
        filter(lang(?name_en) = "en")
    }
    OPTIONAL {
        ?artsdata schema:name ?name_none .
        filter(lang(?name_none) = "")
    }
    bind(coalesce(?name_fr,?name_none,?name_en) as ?nom)
    filter(contains(str(?artsdata),"http://kg.artsdata.ca/resource/K"))
    OPTIONAL {
        ?artsdata schema:sameAs ?wikidata .
        filter(contains(str(?wikidata),"http://www.wikidata.org/entity/Q"))
    }
    ?artsdata schema:address ?address .
    ?address schema:streetAddress ?streetAddresses .
    ?address  schema:addressRegion ?regions .
    OPTIONAL {
        ?address schema:addressCountry ?countries ;
                 schema:addressLocality ?localities ;
                 schema:postalCode ?postalCodes .
    }
    filter(str(?regions) = "QC" || str(?regions) = "Quebec" || str(?regions) = "Québec")
}
group by  ?nom ?artsdata   ?wikidata ?contained_in
