PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX schema: <http://schema.org/>
select 
(sample(?org_name) as ?org) 
?url 
?pages
?crawl_start
?crawl_end
?event_count
?view_events
where {
    ?spiderfeed a schema:DataFeed ;
    schema:dataFeedElement ?url .
    ?org schema:url ?url ;
    schema:name ?org_name .
    ?crawl prov:used ?url ;
    a prov:Activity ;
    prov:wasInformedBy/schema:name ?activity ;
    schema:additionalProperty/schema:value ?pages ;
    prov:startedAtTime ?crawl_start ;
    prov:endedAtTime ?crawl_end .
    OPTIONAL {
        ?artifact_dataset prov:wasGeneratedBy ?crawl .
        OPTIONAL {
            ?artifact_dataset  <http://rdfs.org/ns/void#classPortion> ?portions .
            ?portions <http://rdfs.org/ns/void#class> schema:Event ;
            <http://rdfs.org/ns/void#entities> ?event_count .
        }
        ?graph prov:wasDerivedFrom/<http://xmlns.com/foaf/0.1/primaryTopic>  ?artifact_dataset .
        BIND(CONCAT("<a href='/query/show?sparql=list_events&graph=",str(?graph),"'>View events</a>") as ?view_events)
    }
} group by ?url ?view_events ?pages  ?crawl_start ?crawl_end  ?event_count
